---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: QwietGoTesting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:

  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.16.15' ]

    steps:
    - uses: actions/checkout@v4


    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Setup Environment
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Go Build 
      shell: bash
      run: |
        go build ./...

    - name: NextGen Static Analysis
      run: | 
        export SL_CPG_OPTS="-J-Xms2g -J-Xmx7g"
        export NODE_OPTIONS="--max_old_space_size=4096"
        echo $SL_CPG_OPTS
        ${GITHUB_WORKSPACE}/sl analyze --strict --wait --app go-test-bench --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --go ./cmd/std
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
